version: '3'  # You can specify the Compose version here

services:
  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: poli
      MYSQL_DATABASE: poli
      MYSQL_USER: poli
      MYSQL_PASSWORD: 123

  wordpress:
    image: wordpress:latest
    ports:
      - "3000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: poli
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_USER: poli
      WORDPRESS_DB_NAME: poli
    volumes:
      - wordpress_data:/var/www/html

volumes:
  wordpress_data:
  db_data:

